# This code is used to:
# 1) 
# 2)
# 3)

# To run this script, we need data as follows:
# 1) Gridded HA expanded from EARTHSTAT (Generated by running the Cal_HA_Step1.py code): /lustre/nobackup/WUR/ESG/zhou111/Data/Processed/Fertilization/HA_P_Fert_60yr
# 2) Country boundaries (Contains in the R package cshapes)
#    The cshapes package could be downloaded following this instruction: https://icr.ethz.ch/data/cshapes/r-package/
#    Another package "terra" could be do    

# 3) Histortical FAOSTAT harvest area by crop, could be downloaded from: https://www.fao.org/faostat/en/#data/QCL 


#Loading libraries used in the code 
rm(list=ls())
library(sf)
library(terra)      
library(cshapes) # Country boundaries: do not need to download from somewhere else   
library(tidyverse)  
library(readxl)
library(exactextractr)
library(readr)
library(ncdf4)
library(ggplot2)
library(stringr)

# -------------- Define the redistribution function -------------
# Function to redistribute excess values to neighboring cells
# Function (expanded gridded HA, maximum area of each grid, cropname)
redistribute_excess <- function(eq_map, max_map, name) {
  # Calculate the difference map: positive values indicate excess
  diff_map <- eq_map - max_map
  # Identify excess: cells where the difference is positive
  excess_cells <- diff_map > 0
  # Mask to keep only cells with excess
  diff_map_excess <- terra::mask(diff_map, excess_cells, maskvalue = FALSE) 
  # For cells with excess, cap their values to the maximum
  eq_map[excess_cells] <- max_map[excess_cells]
  # Calculate the total excess that needs redistribution
  total_excess <- global(diff_map_excess, fun = 'sum', na.rm = TRUE)
  
  # Check if the total excess is valid (positive)
  if (!is.na(total_excess) && total_excess > 0) {
    
    # Find cells that can receive the excess (non-zero cells that are below their max)
    valid_cells <- eq_map > 0 & eq_map < max_map

    # Calculate proportionate redistribution
    total_valid_cells <- sum(valid_cells, na.rm = TRUE)
    total_excess_cells <- global(valid_cells, fun = 'sum', na.rm = TRUE)
    proportion <- total_excess/total_excess_cells
    proportion_value <- proportion[name, "sum"]
    eq_map[valid_cells] <- eq_map[valid_cells] + proportion_value
    
    # Ensure no cell exceeds its maximum after redistribution
    diff_map <- eq_map - max_map
    # Identify excess: cells where the difference is positive
    excess_cells <- diff_map > 0
    eq_map[excess_cells] <- max_map[excess_cells]
  }
  return(eq_map)
}

# ------------------- Data reading starts from here ------------------
# 1) The gridded HA generated in Step1 will be read later
# 2) Loading in the national boundaries data depending on the relevand dates
df_national_bound_1 <- cshp(date = as.Date("1991-01-01"))
df_national_bound_2 <- cshp(date = as.Date("1992-11-11"))
df_national_bound_3 <- cshp(date = as.Date("1993-01-01"))
df_national_bound_4 <- cshp(date = as.Date("2006-10-10"))
df_national_bound_5 <- cshp(date = as.Date("2011-01-01"))
df_national_bound_6 <- cshp(date = as.Date("2012-01-01"))
# 3) Histortical FAOSTAT harvest area by crop
FAOSTAT_HA <- read_excel("/lustre/nobackup/WUR/ESG/zhou111/Data/Raw/FAOSTAT/FAOSTAT_HA_1961-2023.xlsx")

# ------------ Match the generated HA to FAOSTAT ----------------
# Crops that we are interested in
crop_data_all <- data.frame(
  crop_code = c("15", "56", "27", "236"),
  crop_name = c("Wheat", "Maize", "Rice", "Soybean")
)

# Here we start with the actual map building 
# We first loop over the different crops 
for (i in 1:nrow(crop_data_all)) {
  crop <- crop_data_all$crop_code[i]
  crop_name <- crop_data_all$crop_name[i]
  
  # Following this we loop over the relevant years (here limited for performance)
  # And select the correct country boundary map based on the year
  for (year in 1961:2020){
    if (year < 1992) {
      df_national_bound <- df_national_bound_1
    } else if (year == 1992) {
      df_national_bound <- df_national_bound_2
    } else if (year < 2006) {
      df_national_bound <- df_national_bound_3
    } else if (year < 2011) {
      df_national_bound <- df_national_bound_4
    } else if (year < 2012) {
      df_national_bound <- df_national_bound_5
    } else {
      df_national_bound <- df_national_bound_6
    }
    
    # Here we fetch the correct map of the crop and year from the EQ1 output
    file_path_rast <- paste("/lustre/nobackup/WUR/ESG/zhou111/Data/Processed/Fertilization/HA_P_Fert_60yr/EQ1_", crop_name, "_", year, ".tiff", sep = "")
    file_var_name <- paste("EQ1_", crop_name, "_", year, sep = "")
    eq_1_maps <- rast(file_path_rast)
    
    # Get the sum area of each country
    Area_M_Sum <- terra::extract(eq_1_maps,df_national_bound,sum)
    colnames(Area_M_Sum)[2] <- "Org_HA"  # Rename the new created column
    Area_M_Sum$Area <- df_national_bound$country_name 

    # Calculate the correction ratio of each country 
    FAOSTAT_HA_crop_year <- FAOSTAT_HA %>% filter(Year == year & Item_Code == crop)
    Area_M_Sum <- Area_M_Sum %>% left_join(., FAOSTAT_HA_crop_year, by = "Area")
    Area_M_Sum$Corr_Ratio <- Area_M_Sum$FAO_HA/Area_M_Sum$Org_HA # The variable name of HA from FAOSTAT is "FAO_HA"
    Area_M_Sum$Corr_Ratio[is.na(Area_M_Sum$Corr_Ratio)] <- 1 # If FAO does not have record, then we set the Corr_Ratio to 1

    # Create a new raster file
    raster_country <- rast(eq_1_maps, vals = 0)

    df_national_bound <- df_national_bound %>%
      left_join(Area_M_Sum, by = "Area")
    raster_country <- rasterize(df_national_bound, raster_country, field = "Corr_Ratio", fun = "mean")
    corrected_raster <- eq_1_maps * raster_country  # Apply correction factor
    writeRaster(corrected_raster, paste0("HA", crop_name, "_", year, ".tif"), format = "GTiff", overwrite = TRUE)
  }

}